#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-compiler-plugin
Version  : 3.7.0
Release  : 1
URL      : https://github.com/apache/maven-compiler-plugin/archive/maven-compiler-plugin-3.7.0.tar.gz
Source0  : https://github.com/apache/maven-compiler-plugin/archive/maven-compiler-plugin-3.7.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.7.0/maven-compiler-plugin-3.7.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.7.0/maven-compiler-plugin-3.7.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
